apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: senteval-results-claim
  labels:
    app: SentEval
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---

apiVersion: batch/v1
kind: Job
metadata:
  name: senteval-job-pubmed-sector-v3
spec:
  template:
    spec:
      containers:
      - name: senteval-gpu
        image: registry.datexis.com/toberhauser/senteval-gpu:1.2.0
        volumeMounts:
          -  name: senteval-results-claim
             mountPath: /root/results
        env:
          - name: ENCODERURL
            value: "http://cluster.datexis.com:32056/v2/encode/tokens"
          - name: ENCODERTYPE
            value: "SENTENCE"
          - name: TOKENAGGREGATION
            value: "NONE"
          - name: SENTEVAL_KFOLD
            value: "10"
          - name: SENTEVAL_CLASSIFIER_NHID
            value: "0"
          - name: SENTEVAL_CLASSIFIER_OPTIM
            value: "adam"
          - name: SENTEVAL_CLASSIFIER_BATCHSIZE
            value: "64"
          - name: SENTEVAL_CLASSIFIER_TENACITY
            value: "5"
          - name: SENTEVAL_CLASSIFIER_EPOCHSIZE
            value: "4"
          - name: SENTEVAL_CLASSIFIER_DROPOUT
            value: "0.0"
          - name: LOGLEVEL
            value: "INFO"
        resources:
          limits:
            nvidia.com/gpu: 1
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
      nodeSelector:
        gpu: k80
      volumes:
        - name: senteval-results-claim
          persistentVolumeClaim:
            claimName: senteval-results-claim
