apiVersion: batch/v1
kind: Job
metadata:
  name: senteval-job-elmo-sector-max
spec:
  template:
    spec:
      containers:
      - name: senteval-gpu
        image: registry.datexis.com/rschneider/senteval-gpu:ffbf1a1
        volumeMounts:
          -  name: senteval-results-claim
             mountPath: /root/results
        env:
          - name: ENCODERURL
            value: "http://cluster.datexis.com:30813/embed/sentences"
          - name: ENCODERTYPE
            value: "SENTENCE"
          - name: TOKENAGGREGATION
            value: "NONE"
          - name: SENTEVAL_KFOLD
            value: "10"
          - name: SENTEVAL_CLASSIFIER_NHID
            value: "0"
          - name: SENTEVAL_CLASSIFIER_OPTIM
            value: "adam"
          - name: SENTEVAL_CLASSIFIER_BATCHSIZE
            value: "64"
          - name: SENTEVAL_CLASSIFIER_TENACITY
            value: "5"
          - name: SENTEVAL_CLASSIFIER_EPOCHSIZE
            value: "4"
          - name: SENTEVAL_CLASSIFIER_DROPOUT
            value: "0.0"
          - name: LOGLEVEL
            value: "DEBUG"
          - name: TASKS
            value: "WikiSection, PubMedSection"
          - name: TIMEOUT
            value: "90"
        resources:
          requests:
            memory: 10Gi
          limits:
            nvidia.com/gpu: 1
            memory: 10Gi
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
      nodeSelector:
        gpu: k80
      volumes:
        - name: senteval-results-claim
          persistentVolumeClaim:
            claimName: senteval-results-claim
