apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: senteval-results-claim
  labels:
    app: SentEval
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: shared
---

apiVersion: batch/v1
kind: Job
metadata:
  name: senteval-job-knowbert
spec:
  template:
    spec:
      containers:
      - name: senteval-gpu
        image: registry.datexis.com/toberhauser/senteval-gpu:1.5.0
        volumeMounts:
          -  name: senteval-results-claim
             mountPath: /root/results
        env:
          - name: LOGLEVEL
            value: "DEBUG"
          - name: ENCODERURL
            value: "http://knowbert-rest-service.toberhauser.svc.cluster.local/embed/sentences"
          - name: ENCODERTYPE
            value: "SENTENCE"
          - name: TOKENAGGREGATION
            value: "NONE"
          - name: SENTEVAL_KFOLD
            value: "10"
          - name: SENTEVAL_CLASSIFIER_NHID
            value: "0"
          - name: SENTEVAL_CLASSIFIER_OPTIM
            value: "adam"
          - name: SENTEVAL_CLASSIFIER_BATCHSIZE
            value: "64"
          - name: SENTEVAL_CLASSIFIER_TENACITY
            value: "5"
          - name: SENTEVAL_CLASSIFIER_EPOCHSIZE
            value: "4"
          - name: SENTEVAL_CLASSIFIER_DROPOUT
            value: "0.0"
        resources:
          limits:
            nvidia.com/gpu: 1
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
      nodeSelector:
        gpu: k80
      volumes:
        - name: senteval-results-claim
          persistentVolumeClaim:
            claimName: senteval-results-claim
