apiVersion: batch/v1
kind: Job
metadata:
  name: senteval-weaver-wikisec-elmo-128-max
spec:
  template:
    metadata:
      labels:
        app: senteval
        experiment: dimensionality
    spec:
      containers:
      - name: senteval-gpu
        image: registry.datexis.com/rschneider/senteval-gpu:2387837
        volumeMounts:
          -  name: senteval-results-claim
             mountPath: /root/results
        env:
          - name: ENCODERURL
            value: "http://cluster.datexis.com:32554/v2/encode/tokens"
          - name: ENCODERTYPE
            value: "SENTENCE"
          - name: TOKENAGGREGATION
            value: "NONE"
          - name: SENTEVAL_KFOLD
            value: "10"
          - name: SENTEVAL_CLASSIFIER_NHID
            value: "0"
          - name: SENTEVAL_CLASSIFIER_OPTIM
            value: "adam"
          - name: SENTEVAL_CLASSIFIER_BATCHSIZE
            value: "64"
          - name: SENTEVAL_CLASSIFIER_TENACITY
            value: "5"
          - name: SENTEVAL_CLASSIFIER_EPOCHSIZE
            value: "4"
          - name: SENTEVAL_CLASSIFIER_DROPOUT
            value: "0.0"
          - name: LOGLEVEL
            value: "INFO"
          - name: TASKS
            value: "STS12, STS13, STS14, STS15, STS16, MR, CR, MPQA, SUBJ, SST2, SST5, TREC, MRPC, SICKEntailment, SICKRelatedness, STSBenchmark, Length, WordContent, Depth,TopConstituents, BigramShift, Tense, SubjNumber, ObjNumber, OddManOut, CoordinationInversion, WikiSection"
        resources:
          requests:
            memory: 10Gi
          limits:
            nvidia.com/gpu: 1
            memory: 10Gi
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
      nodeSelector:
        gpu: k80
      volumes:
        - name: senteval-results-claim
          persistentVolumeClaim:
            claimName: senteval-results-claim
